---
###########
# Crontab #
###########

- name: "replace /bluebird with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "linuxnfs-1.fyre.ibm.com:/bluebird /bluebird   nfs     defaults        0 0"
    line: "s2186ffv.rtp.raleigh.ibm.com:/bluebird /bluebird   nfs     defaults        0 0"
  tags: mountswap
  
- name: "replace /cores with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "linuxnfs-1.fyre.ibm.com:/cores /cores   nfs     defaults        0 0"
    line: "s2186ffv.rtp.raleigh.ibm.com:/cores /cores   nfs     defaults        0 0"
  tags: mountswap
  
- name: "replace /team with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "9.37.250.190:/rt-rtpnfs/team_new /team nfs defaults,rsize=8192,wsize=8192,hard,intr 1 2"
    line: "s2186ffv.rtp.raleigh.ibm.com:/team /team   nfs     defaults        0 0"
  tags: mountswapteam
  
- name: "replace comment"
  lineinfile:
    path: "/etc/fstab"
    regexp: "#GPFS for new /team mount"
    line: "#Dedicated RTP Based LinuxNFS"
  tags: mountswapteam
    
- name: mount all
  command: mount -a
  args:
    warn: no
  become: true
  tags: mountswapteam
  
- name: "replace comment"
  lineinfile:
    path: "/etc/fstab"
    regexp: "9.37.250.190:/rt-rtpnfs/team_new /team nfs defaults,rsize=8192,wsize=8192,hard,intr 1 2"
    line: ""
  tags: mountswapteam
  
- name: Copy a auth script
  copy:
    src: /Vendor_Files/auth.exp
    dest: /
    mode: '755'
  tags: auth 
  
- name: Set timezone to America/Toronto
  timezone:
    name: America/Toronto
  tags: timezone    

- name: "append new line EOF fstab"
  lineinfile:
    path: "/etc/fstab"
    line: "#Temporary NFS mounts for testing new VMFARM system
    
linuxnfs-1.fyre.ibm.com:/bluebird /bluebird   nfs     defaults        0 0

linuxnfs-1.fyre.ibm.com:/cores /cores   nfs     defaults        0 0

#New GPFS /team share our of RTP

9.37.250.96:/rt-rtpnfs/team_new /team nfs defaults 0 0"
    insertafter: "EOF"   
  tags: mounts
  
- name: Ensure group "bluebird" exists
  group:
    name: bluebird
    gid: 1020
    state: present
  tags: j9build

- name: Add the user 'j9build' with a specific uid and a primary group of 'admin'
  user:
    name: j9build
    comment: j9build
    uid: 4068
    group: bluebird
  tags: j9build
  
- name: "set j9build bluebird homedir"
  lineinfile:
    path: "/etc/passwd"
    regexp: "j9build:x:4068:1020:j9build:/home/j9build:/bin/bash"
    line: "j9build:x:4068:1020:j9build:/bluebird/j9build:/bin/bash"
  tags: j9build
  
#sles packages
- name: install packages
  zypper:
    name: 
      - expect
      - telnet
      - bind-utils
      - bison                         # OpenJ9
      - cpio
      - curl
      - flex
      - gcc
      - gcc-c++
      - glibc
      - glibc-devel
      - libdw1
      - libelf1
      - make
      - pkg-config
      - unzip
      - wget
      - zip
      - java-1_8_0-openjdk
      - git-core
      - libelf0
      - libfreetype6
      - libXext6
      - libXi6                        # JDK12+ compilation
      - libXrandr2                    # JDK12+ compilation
      - libXrender1
      - libXt6
      - libXtst6
      - Mesa-libGL1
      - ntp
      - perl-CPAN-Meta
      - glibc-32bit                   # a dependency required for executing a 32-bit C binary
      - glibc-devel-32bit             # a dependency required for executing a 32-bit C binary
      - libstdc++6-32bit              # a dependency required for executing a 32-bit C binary
      - libelf0-32bit                 # a dependency required for executing a 32-bit C binary
      - libelf0-debuginfo-32bit       # a dependency required for executing a 32-bit C binary
      - libstdc++-devel-32bit         # a dependency required for executing a 32-bit C binary
      - libXtst6-32bit                # a dependency required for executing a 32-bit C binary
    state: latest
  tags: packagesle
  
- name: Remove the ant ant-contrib packages
  yum:
    name: 
      - ant
      - ant-contrib
    state: absent
  tags: packagesle
  
- name: Auth to BSO at reboot
  cron:
    name: "Auth to BSO reboot"
    special_time: reboot
    job: "/./auth.exp"
  tags: cron

- name: auth every 6 hours
  cron:
    name: "Auth to BSO Automatically"
    minute: "0"
    hour: "*/6"
    user: root
    job: "/./auth.exp"
  tags: cron
  
- name: Create /cores dir
  file:
    path: /cores
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs

- name: Create /bluebird dir
  file:
    path: /bluebird
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs
  
- name: Create /team dir
  file:
    path: /team
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs
