---
###########
# Crontab #
###########

- name: "replace /bluebird with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "linuxnfs-1.fyre.ibm.com:/bluebird /bluebird   nfs     defaults        0 0"
    line: "s2186ffv.rtp.raleigh.ibm.com:/bluebird /bluebird   nfs     defaults        0 0"
  tags: mountswap
  
- name: "replace /cores with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "linuxnfs-1.fyre.ibm.com:/cores /cores   nfs     defaults        0 0"
    line: "s2186ffv.rtp.raleigh.ibm.com:/cores /cores   nfs     defaults        0 0"
  tags: mountswap
  
- name: "replace /team with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "9.37.250.96:/rt-rtpnfs/team_new /team nfs defaults 0 0"
    line: "s2186ffv.rtp.raleigh.ibm.com:/team /team   nfs     defaults        0 0"
  tags: mountswap
  
- name: "replace comment"
  lineinfile:
    path: "/etc/fstab"
    regexp: "#Temporary NFS mounts for testing new VMFARM system"
    line: "#Dedicated RTP Based LinuxNFS"
  tags: mountswap
  
- name: "replace comment"
  lineinfile:
    path: "/etc/fstab"
    regexp: "#New GPFS /team share our of RTP"
    line: ""
  tags: mountswap

- name: Copy a auth script
  copy:
    src: /Vendor_Files/auth.exp
    dest: /
    mode: '755'
  tags: auth 
  
- name: Set timezone to America/Toronto
  timezone:
    name: America/Toronto
  tags: timezone    

- name: "append new line EOF fstab"
  lineinfile:
    path: "/etc/fstab"
    line: "#Temporary NFS mounts for testing new VMFARM system
    
linuxnfs-1.fyre.ibm.com:/bluebird /bluebird   nfs     defaults        0 0

linuxnfs-1.fyre.ibm.com:/cores /cores   nfs     defaults        0 0

#New GPFS /team share our of RTP

9.37.250.96:/rt-rtpnfs/team_new /team nfs defaults 0 0"
    insertafter: "EOF"   
  tags: mounts
  
- name: Ensure group "bluebird" exists
  group:
    name: bluebird
    gid: 1020
    state: present
  tags: j9build

- name: Add the user 'j9build' with a specific uid and a primary group of 'admin'
  user:
    name: j9build
    comment: j9build
    uid: 4068
    group: bluebird
  tags: j9build
  
- name: "set j9build bluebird homedir"
  lineinfile:
    path: "/etc/passwd"
    regexp: "j9build:x:4068:1020:j9build:/home/j9build:/bin/bash"
    line: "j9build:x:4068:1020:j9build:/bluebird/j9build:/bin/bash"
  tags: j9build
  
#sles packages
- name: install packages
  zypper:
    name: 
      - expect
      - telnet
      - bind-utils
      - bison                         # OpenJ9
      - cpio
      - curl
      - flex
      - gcc
      - gcc-c++
      - glibc
      - glibc-devel
      - libdw1
      - libelf1
      - make
      - unzip
      - wget
      - zip
      - alsa-devel
      - cups-devel
      - fontconfig-devel
      - java-1_8_0-openjdk
      - libcurl-devel
      - libelf-devel
      - libnuma-devel
      - libX11-devel
      - libXext-devel
      - libXi-devel
      - libXrandr-devel                 # JDK12+ compilation
      - libXrender-devel
      - libXt-devel
      - libXtst-devel
      - gcc
      - gcc-c++
      - perl
      - xorg-x11
      - xorg-x11-server
      - xorg-x11-server-extra
      - glibc-locale                  # Internationalization tests
    state: latest
  tags: packagesle
  
- name: Remove the ant ant-contrib packages
  yum:
    name: 
      - ant
      - ant-contrib
    state: absent
  tags: packagesle
  
- name: Auth to BSO at reboot
  cron:
    name: "Auth to BSO reboot"
    special_time: reboot
    job: "/./auth.exp"
  tags: cron

- name: auth every 6 hours
  cron:
    name: "Auth to BSO Automatically"
    minute: "0"
    hour: "*/6"
    user: root
    job: "/./auth.exp"
  tags: cron
  
- name: Create /cores dir
  file:
    path: /cores
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs

- name: Create /bluebird dir
  file:
    path: /bluebird
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs
  
- name: Create /team dir
  file:
    path: /team
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs
