---
###########
# Crontab #
###########

- name: Ensure group "bluebird" exists
  group:
    name: bluebird
    gid: 1020
    state: present
  tags: crontab

- name: Add the user 'j9build' with a specific uid and a primary group of 'admin'
  user:
    name: j9build
    comment: j9build
    uid: 4068
    group: bluebird
  tags: crontab
  
- name: install packages
  yum:
    name: 
      - expect
      - telnet
      - numactl-devel
      - glibc.i686                    # a dependency required for executing a 32-bit C binary
      - glibc-devel.i686              # a dependency required for executing a 32-bit C binary
      - libstdc++.i686                # a dependency required for executing a 32-bit C binary
      - libstdc++
      - acl
      - perl
      - perl-Digest-SHA
      - xorg-x11-xauth
      - xorg-x11-server-Xvfb
      - zlib-devel
      - perl-devel
      - expat-devel
      - libcurl-devel
      - ntp
      - alsa-lib-devel
      - autoconf
      - bind-utils
      - bison                         # OpenJ9
      - bzip2
      - cpio
      - cups-devel
      - elfutils-libelf-devel
      - flex                          # OpenJ9
      - fontconfig-devel
      - freetype-devel
      - gcc
      - gcc-c++
      - gettext
      - glibc
      - glibc-common
      - glibc-devel
      - gmp-devel
      - libcurl-devel
      - libdwarf-devel                # OpenJ9
      - libffi-devel
      - libmpc-devel
      - libpng-devel
      - libXext-devel
      - libXi-devel                   # JDK12+ compilation
      - libXrandr-devel               # JDK12+ compilation
      - libXrender-devel
      - libXt-devel
      - libXtst-devel
      - make
      - mesa-libGL-devel
      - mpfr-devel
      - openssl-devel
      - perl-devel
      - pkgconfig
      - systemtap-sdt-devel
      - unzip
      - wget
      - xz
      - zip
    state: latest
  tags: crontab
  
- name: Remove the ant ant-contrib packages
  yum:
    name: 
      - ant
      - ant-contrib
    state: absent
  tags: crontab
  
- name: Set timezone to America/Toronto
  community.general.timezone:
    name: America/Torotno
  tags: crontab    

- name: Creates an entry like "auth file"
  cron:
    name: "Auth to BSO Automatically"
    minute: "0"
    hour: "*/6"
    user: root
    job: "/./auth.exp"
  tags: crontab
  
- name: Create /cores dir
  file:
    path: /cores
    state: directory
    mode: '0755'
  tags: crontab

- name: Create /cores dir
  file:
    path: /cores
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: crontab

- name: Create /bluebird dir
  file:
    path: /bluebird
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: crontab
  
- name: Create /team dir
  file:
    path: /team
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: crontab
  
#- name: Update FSTAB with mounts
 #lineinfile:
  #      dest: /etc/fstab
  #      line: "#Temporary NFS mounts for testing new VMFARM system
#linuxnfs-1.fyre.ibm.com:/bluebird /bluebird   nfs     defaults        0 0
#linuxnfs-1.fyre.ibm.com:/cores /cores   nfs     defaults        0 0"
#  tags: crontab

#New GPFS /team share our of RTP
9.37.250.96:/rt-rtpnfs/team_new /team nfs defaults 0 0"
        owner: root
  tags: crontab        