---
###########
# Crontab #
###########

- name: "replace /bluebird with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "s2186ffv.rtp.raleigh.ibm.com:/bluebird /bluebird   nfs     defaults        0 0"
    line: "linuxnfs.ottawa.ibm.com:/bluebird /bluebird nfs vers=3,rw,nodev,nosuid,soft,nolock"
  tags: mountswap
  
- name: "replace /cores with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "s2186ffv.rtp.raleigh.ibm.com:/cores /cores  nfs     defaults        0 0"
    line: "linuxnfs.ottawa.ibm.com:/data/cores /cores nfs defaults,rsize=8192,wsize=8192,hard,intr"
  tags: mountswap
  
- name: "replace /team with new linuxfs"
  lineinfile:
    path: "/etc/fstab"
    regexp: "s2186ffv.rtp.raleigh.ibm.com:/team /team   nfs     defaults        0 0"
    line: "linuxnfs.ottawa.ibm.com:/team /team nfs vers=3,rw,nodev,nosuid,soft,nolock"
  tags: mountswapteam
  
- name: "replace comment"
  lineinfile:
    path: "/etc/fstab"
    regexp: "#Dedicated RTP Based LinuxNFS"
    line: ""
  tags: mountswapteam

- name: "replace comment"
  lineinfile:
    path: "/etc/fstab"
    regexp: "9.37.250.190:/rt-rtpnfs/team_new /team nfs defaults,rsize=8192,wsize=8192,hard,intr 1 2"
    line: ""
  tags: mountswapteam1
  
- name: Copy a auth script
  copy:
    src: /Vendor_Files/auth.exp
    dest: /
    mode: '755'
  tags: auth 
   
- name: Ensure group "bluebird" exists
  group:
    name: bluebird
    gid: 1020
    state: present
  tags: j9build

- name: Add the user 'j9build' with a specific uid and a primary group of 'admin'
  user:
    name: j9build
    comment: j9build
    uid: 4068
    group: bluebird
  tags: j9build
  
- name: "set j9build bluebird homedir"
  lineinfile:
    path: "/etc/passwd"
    regexp: "j9build:x:4068:1020:j9build:/home/j9build:/bin/bash"
    line: "j9build:x:4068:1020:j9build:/bluebird/j9build:/bin/bash"
  tags: j9build
  
#sles packages
- name: install packages
  yum:
    name: 
      - expect
      - telnet
      - gcc
      - gcc-c++
      - unzip
      - zlib-devel
      - perl-devel
      - libcurl-devel
      - openssl-devel
      - mercurial
      - perl
      - xorg-x11-xauth
      - xorg-x11-server-Xorg
      - xorg-x11-server-Xvfb
      - alsa-lib-devel
      - autoconf
      - bind-utils
      - bison                         # OpenJ9
      - bzip2
      - cpio
      - cups-devel
      - elfutils-libelf-devel
      - file
      - flex                          # OpenJ9
      - fontconfig-devel
      - freetype-devel
      - gcc
      - gcc-c++
      - gettext
      - glibc
      - glibc-common
      - glibc-devel
      - gmp-devel
      - java-1.8.0-openjdk-devel
      - libcurl-devel
      - libdwarf-devel                # OpenJ9
      - libpng-devel
      - libXext-devel
      - libXi-devel                   # JDK12+ compilation
      - libXrandr-devel               # JDK12+ compilations
      - libXrender-devel
      - libXt-devel
      - libXtst-devel
      - make
      - mesa-libGL-devel
      - mpfr-devel
      - numactl-devel                 # OpenJ9
      - openssl-devel
      - perl-DBI
      - perl-devel
      - perl-Digest-SHA
      - perl-GD
      - perl-libwww-perl
      - perl-Time-HiRes
      - systemtap-sdt-devel
      - unzip
      - wget
      - which
      - xz
      - zip
    state: latest
  tags: packagesle
  
- name: Remove the ant ant-contrib packages
  yum:
    name: 
      - ant
      - ant-contrib
    state: absent
  tags: packagesle
  
- name: Auth to BSO at reboot
  cron:
    name: "Auth to BSO reboot"
    special_time: reboot
    job: "/./auth.exp"
  tags: cron

- name: auth every 6 hours
  cron:
    name: "Auth to BSO Automatically"
    minute: "0"
    hour: "*/6"
    user: root
    job: "/./auth.exp"
  tags: cron
  
- name: Create /cores dir
  file:
    path: /cores
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs

- name: Create /bluebird dir
  file:
    path: /bluebird
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs
  
- name: Create /team dir
  file:
    path: /team
    owner: j9build
    group: bluebird
    state: directory
    mode: '0755'
  tags: dirs
  
- name: Set timezone to America/Toronto
  timezone:
    name: America/Toronto
  tags: timezone    

- name: "append new line EOF fstab"
  lineinfile:
    path: "/etc/fstab"
    line: "linuxnfs.ottawa.ibm.com:/service /service nfs defaults,rsize=8192,wsize=8192,hard,intr"
    insertafter: "EOF"   
  tags: mounts
  
- name: mount all
  command: mount -a
  args:
    warn: no
  become: true
  tags: mountall
