---
###########
# Crontab #
###########
- name: Creates an entry like "auth file"
  cron:
    name: "a job for reboot"
    minute: "0"
    hour: "*/6"
    user: root
    job: "/auth.exp"
  tags: crontab
