---
###########
# Crontab #
###########

- name: install expect package
  yum:
    name: expect
    state: latest
  tags: crontab
  
- name: install telnet package
  yum:
    name: telnet
    state: latest
  tags: crontab
  
- name: Run auth script
   script: /./auth.exp
  tags: crontab

- name: Creates an entry like "auth file"
  cron:
    name: "Auth to BSO Automatically"
    minute: "0"
    hour: "*/6"
    user: root
    job: "/./auth.exp"
  tags: crontab
